version: "3.9"

networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
  backend:
    driver: bridge

services:
  redis:
    image: redis:6-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass cFzNJk3g2o
    networks:
      - redis
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: 
      - ./variables.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: choydy
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: 
      - ./variables.env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ndtao2020@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678x@X
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  backend:
    image: taoqn/choydy-com
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./data/backend:/work/upload
    networks:
      - redis
      - postgres
      - backend
    env_file: 
      - ./variables.env
    environment:
      QUARKUS_REDIS_HOSTS: redis://default:cFzNJk3g2o@redis:6379
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/choydy
      QUARKUS_KEYSTORE_PATH: /work/key/keystore.jks

#  nginx:
#    image: nginx:1.21-alpine
#    restart: always
#    depends_on:
#      - backend
#    networks:
#      - backend
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    ports:
#      - 80:80
#      - 443:443
