version: "3.9"

networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
  minio:
    driver: bridge
  backend:
    driver: bridge

services:
  redis:
    image: redis:6-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass cFzNJk3g2o
    networks:
      - redis
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: 
      - ./variables.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: choydy

  minio:
    image: minio/minio:RELEASE.2021-12-10T23-03-39Z
    restart: always
    networks:
      - minio
    volumes:
      - /mnt/data:/data
    env_file:
      - ./variables.env
    ports:
      - 9001:9001
    command: server /data --console-address ":9001"

  backend:
    image: taoqn/choydy-com
    restart: always
    depends_on:
      - redis
      - postgres
      - minio
    ports:
      - 8080:8080
    volumes:
      - ./data/backend:/work/upload
    networks:
      - redis
      - postgres
      - minio
      - backend
    env_file: 
      - ./variables.env
    environment:
      QUARKUS_REDIS_HOSTS: redis://default:cFzNJk3g2o@redis:6379
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/choydy
      QUARKUS_KEYSTORE_PATH: /work/key/keystore.jks

#  nginx:
#    image: nginx:1.21-alpine
#    restart: always
#    depends_on:
#      - backend
#    networks:
#      - backend
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    ports:
#      - 80:80
#      - 443:443
